### ISSUE TITLE
Fonts werken niet in 4.3.13

### ISSUE THREAD

**Issue by timspiering** [zicht/tinymce-bundle#3]
[https://github.com/zicht/tinymce-bundle/tree/release/1.x/src/Zicht/Bundle/TinymceBundle/Resources/public/js/vendor/tinymce/4.3.13/skins/lightgray/fonts](url)

De fonts lijken leeg te zijn waardoor je de foutmelding krijgt dat ze niet gedecode kunnen worden.

**Comment by erik-zicht** [comment]
Fixed in PR #5
